var BASE_URL='https://truyenhub.net';
var IOS_UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1';
function thAbs(h){h=String(h||'');if(!h)return '';if(h.indexOf('http://')===0||h.indexOf('https://')===0)return h;if(h.charAt(0)!='/')h='/'+h;return BASE_URL+h;}
function thEnt(s){s=String(s||'');s=s.replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');return s.replace(/&#(x?[0-9a-f]+);/gi,function(a,n){var v=n.charAt(0).toLowerCase()==='x'?parseInt(n.substring(1),16):parseInt(n,10);return isNaN(v)?a:String.fromCharCode(v);});}
function thAttr(tag,name){var r=new RegExp('\\b'+name+'\\s*=\\s*(["\\\'])'+'([^"\\\']*)'+'\\1','i'),m=r.exec(String(tag||''));return m?thEnt(m[2]):'';}
function thText(s){s=String(s||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' ');return thEnt(s).replace(/\s+/g,' ').replace(/^\s+|\s+$/g,'');}
function thNfc(s){s=String(s||'');try{if(s.normalize)s=s.normalize('NFC');}catch(e){}return s;}
function thParse(h){var re=/<a\b[^>]*href\s*=\s*(["'])([^"']*\/truyen\/[^"']+)\1[^>]*>[\s\S]*?<\/a>/gi,m,out=[],seen={};while((m=re.exec(String(h||'')))!==null){var full=m[0],href=thAbs(thEnt(m[2]));if(href.indexOf(BASE_URL+'/truyen/')!==0||href.indexOf('/chuong-')>=0||seen[href])continue;var gt=full.indexOf('>'),open=gt>=0?full.substring(0,gt+1):full,inner=gt>=0?full.substring(gt+1,full.length-4):'',im=/<img\b[^>]*>/i.exec(inner),img=im?im[0]:'',name=thAttr(open,'title')||thAttr(img,'alt')||thText(inner);name=name.replace(/^Bìa truyện\s+/i,'').replace(/^\s+|\s+$/g,'');if(!name)continue;var cover=thAttr(img,'data-src')||thAttr(img,'data-lazy-src')||thAttr(img,'src')||'';seen[href]=1;out.push({name:name,link:href,cover:thAbs(cover),host:BASE_URL});}return out;}
function execute(query,page){var p=(page===null||page===undefined||page===''||String(page)==='0')?'1':String(page);if(p!=='1')return Response.success([],null);var q=thNfc(String(query||'').replace(/^\s+|\s+$/g,''));if(!q)return Response.success([],null);var r=null;try{r=fetch(BASE_URL+'/tim-kiem',{queries:{keyword:q},headers:{'User-Agent':IOS_UA,'Accept':'text/html,application/xhtml+xml','Referer':BASE_URL+'/'}});}catch(e){}if(!r||!r.ok)return Response.success([],null);var h='';try{h=String(r.text()||'');}catch(e2){}var out=thParse(h);return Response.success(out,null);}
