load('config.js');
function execute() {
    return Response.success([
        { title: "Webnovel", input: "/genre/Webnovel/", script: "gen.js" },
        { title: "Fantasy", input: "/genre/Fantasy/", script: "gen.js" },
        { title: "Systemflow", input: "/genre/Systemflow/", script: "gen.js" },
        { title: "Action", input: "/genre/Action/", script: "gen.js" },
        { title: "Romance", input: "/genre/Romance/", script: "gen.js" },
        { title: "Adventure", input: "/genre/Adventure/", script: "gen.js" },
        { title: "Comedy", input: "/genre/Comedy/", script: "gen.js" },
        { title: "Harem", input: "/genre/Harem/", script: "gen.js" },
        { title: "Urban", input: "/genre/Urban/", script: "gen.js" },
        { title: "Adult", input: "/genre/Adult/", script: "gen.js" },
        { title: "Slice of Life", input: "/genre/Slice+of+Life/", script: "gen.js" },
        { title: "Official Circles", input: "/genre/Official+Circles/", script: "gen.js" },
        { title: "Science fiction", input: "/genre/Science+fiction/", script: "gen.js" },
        { title: "Drama", input: "/genre/Drama/", script: "gen.js" },
        { title: "Mystery", input: "/genre/Mystery/", script: "gen.js" },
        { title: "Supernatural", input: "/genre/Supernatural/", script: "gen.js" },
        { title: "Reincarnation", input: "/genre/Reincarnation/", script: "gen.js" },
        { title: "Game", input: "/genre/Game/", script: "gen.js" },
        { title: "Mature", input: "/genre/Mature/", script: "gen.js" },
        { title: "Martial Arts", input: "/genre/Martial+Arts/", script: "gen.js" },
        { title: "Sci-fi", input: "/genre/Sci-fi/", script: "gen.js" },
        { title: "Psychological", input: "/genre/Psychological/", script: "gen.js" },
        { title: "School Life", input: "/genre/School+Life/", script: "gen.js" },
        { title: "Eastern", input: "/genre/Eastern/", script: "gen.js" },
        { title: "Xianxia", input: "/genre/Xianxia/", script: "gen.js" },
        { title: "Historical", input: "/genre/Historical/", script: "gen.js" },
        { title: "Other", input: "/genre/Other/", script: "gen.js" },
        { title: "Tragedy", input: "/genre/Tragedy/", script: "gen.js" },
        { title: "Xuanhuan", input: "/genre/Xuanhuan/", script: "gen.js" },
        { title: "Smut", input: "/genre/Smut/", script: "gen.js" },
        { title: "Ecchi", input: "/genre/Ecchi/", script: "gen.js" },
        { title: "Shounen", input: "/genre/Shounen/", script: "gen.js" },
        { title: "Josei", input: "/genre/Josei/", script: "gen.js" },
        { title: "Yaoi", input: "/genre/Yaoi/", script: "gen.js" },
        { title: "Seinen", input: "/genre/Seinen/", script: "gen.js" },
        { title: "Horror", input: "/genre/Horror/", script: "gen.js" },
        { title: "Fan-Fiction", input: "/genre/Fan-Fiction/", script: "gen.js" },
        { title: "Gender Bender", input: "/genre/Gender+Bender/", script: "gen.js" },
        { title: "Isekai", input: "/genre/Isekai/", script: "gen.js" },
        { title: "Wuxia", input: "/genre/Wuxia/", script: "gen.js" },
        { title: "Shoujo", input: "/genre/Shoujo/", script: "gen.js" },
        { title: "Yuri", input: "/genre/Yuri/", script: "gen.js" },
        { title: "Sports", input: "/genre/Sports/", script: "gen.js" },
        { title: "Magic", input: "/genre/Magic/", script: "gen.js" },
        { title: "Mecha", input: "/genre/Mecha/", script: "gen.js" },
        { title: "Litrpg", input: "/genre/Litrpg/", script: "gen.js" },
        { title: "System", input: "/genre/System/", script: "gen.js" },
        { title: "Shoujo Ai", input: "/genre/Shoujo+Ai/", script: "gen.js" },
        { title: "Video games", input: "/genre/Video+games/", script: "gen.js" },
        { title: "Anime & comics", input: "/genre/Anime+%26+comics/", script: "gen.js" },
        { title: "Magical realism", input: "/genre/Magical+realism/", script: "gen.js" },
        { title: "Lgbt+", input: "/genre/Lgbt+/", script: "gen.js" },
        { title: "Thriller", input: "/genre/Thriller/", script: "gen.js" },
    ]);
}
