# Frozen Candidate #3 robustness
# Parent: BTC 30d DOWN + BTC RV20 > RV60
# Candidate3: parent + BROAD_DOWN + FUNDING3 <= 0
# IMPORTANT: definition is frozen from prior diagnostic; do not tune.
import json, math, random, statistics
from pathlib import Path

SRC=Path('/tmp/diag/trade_liq_funding_oi_breadth.json')
OUT=Path('/tmp/final8'); OUT.mkdir(parents=True,exist_ok=True)
# This run consumes the prior diagnostic report plus enriched trade rows generated by the companion script.
# Fail explicitly if enriched rows are absent; workflow creates them by running the diagnostic module first.
import sys
sys.path.insert(0,'wave-rider-verify')
import wr_trade_liq_funding_oi_breadth as d
F=d.F; net=d.net; year=d.year; dt=d.dt
P=d.P
C=[a for a in F if a['_x'].get('breadth')=='BROAD_DOWN' and a['_x'].get('fund3')=='NONPOS']

def metrics(xs,bps=6):
    vals=[net(a,bps) for a in xs]; eq=0; peak=0; mdd=0
    for v in vals:
        eq+=v; peak=max(peak,eq); mdd=min(mdd,eq-peak)
    return {'n':len(xs),'net':sum(vals),'avg':statistics.mean(vals) if vals else None,'max_dd':mdd}

def by_month(xs,bps=6):
    z={}
    for a in xs:
        k=dt(a).strftime('%Y-%m'); z[k]=z.get(k,0)+net(a,bps)
    return z

def bootstrap(xs, block=False, n=10000, seed=2515):
    r=random.Random(seed)
    if block:
        bm=by_month(xs); units=list(bm.values()); draws=[sum(r.choice(units) for _ in units)/sum(1 for _ in units) for _ in range(n)]
    else:
        vals=[net(a,6) for a in xs]; draws=[sum(r.choice(vals) for _ in vals)/len(vals) for _ in range(n)]
    draws.sort(); return [draws[int(.025*n)],draws[int(.975*n)-1]]

def concentration(xs):
    s={}
    for a in xs:s[a['symbol']]=s.get(a['symbol'],0)+net(a,6)
    ranked=sorted(s.items(),key=lambda kv:kv[1],reverse=True)
    return {f'drop_top_{k}':sum(net(a,6) for a in xs if a['symbol'] not in {x[0] for x in ranked[:k]}) for k in (1,5,10)}

def summary(xs):
    bm=by_month(xs); total=sum(net(a,6) for a in xs)
    loo={m:total-v for m,v in bm.items()}
    return {'costs':{str(b):metrics(xs,b) for b in (4,6,8,10,12,15,20)},'by_year':{str(y):{str(b):metrics([a for a in xs if year(a)==y],b) for b in (6,8,10,12)} for y in (2024,2025,2026)},'months':bm,'positive_months':sum(v>0 for v in bm.values()),'active_months':len(bm),'leave_one_month_out':{'min':min(loo.values()) if loo else None,'all_positive':all(v>0 for v in loo.values()) if loo else False},'bootstrap_trade95':bootstrap(xs,False),'bootstrap_month95':bootstrap(xs,True),'side':{side:metrics([a for a in xs if str(a.get('side','')).upper()==side],6) for side in ('LONG','SHORT')},'concentration':concentration(xs)}
report={'status':'WR_FROZEN_CANDIDATE3_ROBUSTNESS_COMPLETE','frozen_rule':'BTC30 DOWN + BTC RV20>RV60 + BROAD_DOWN + FUNDING3<=0','warning':'Retrospective robustness validation. No threshold tuning permitted.','candidate3':summary(C),'parent_same_enriched_sample':summary(F)}
json.dump(report,open(OUT/'candidate3_robustness.json','w'),indent=2)
print(json.dumps(report,indent=2))