load('transport.js');
var BASE_URL='https://truyenhub.net';
function thEnt(s){s=String(s||'');s=s.replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');return s.replace(/&#(x?[0-9a-f]+);/gi,function(a,n){var v=n.charAt(0).toLowerCase()==='x'?parseInt(n.substring(1),16):parseInt(n,10);return isNaN(v)?a:String.fromCharCode(v);});}
function thNfc(s){s=String(s||'');try{if(s.normalize)s=s.normalize('NFC');}catch(e){}return s;}
function thFold(s){s=thNfc(s).toLowerCase();try{if(s.normalize)s=s.normalize('NFD');}catch(e){}s=s.replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');return s.replace(/[^a-z0-9]+/g,' ').replace(/^\s+|\s+$/g,'').replace(/\s+/g,' ');}
function thSlug(s){return thFold(s).replace(/\s+/g,'-');}
function thAbs(h){h=String(h||'');if(!h)return '';if(h.indexOf('http://')===0||h.indexOf('https://')===0)return h;if(h.charAt(0)!='/')h='/'+h;return BASE_URL+h;}
function thAttr(tag,name){var r=new RegExp('\\b'+name+'\\s*=\\s*(["\\\'])'+'([^"\\\']*)'+'\\1','i'),m=r.exec(String(tag||''));return m?thEnt(m[2]):'';}
function thText(s){s=String(s||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' ');return thEnt(s).replace(/\s+/g,' ').replace(/^\s+|\s+$/g,'');}
function thParse(h){var re=/<a\b[^>]*href\s*=\s*(["'])([^"']*\/truyen\/[^"']+)\1[^>]*>[\s\S]*?<\/a>/gi,m,out=[],seen={};while((m=re.exec(String(h||'')))!==null){var full=m[0],href=thAbs(thEnt(m[2]));if(href.indexOf(BASE_URL+'/truyen/')!==0||href.indexOf('/chuong-')>=0||seen[href])continue;var gt=full.indexOf('>'),open=gt>=0?full.substring(0,gt+1):full,inner=gt>=0?full.substring(gt+1,full.length-4):'',im=/<img\b[^>]*>/i.exec(inner),img=im?im[0]:'',name=thAttr(open,'title')||thAttr(img,'alt')||thText(inner);name=name.replace(/^Bìa truyện\s+/i,'').replace(/^\s+|\s+$/g,'');if(!name)continue;seen[href]=1;out.push({name:name,link:href,cover:thAbs(thAttr(img,'data-src')||thAttr(img,'src')||''),host:BASE_URL});}return out;}
function thExact(q){var h=thBrowserGet(BASE_URL+'/tim-kiem?keyword='+encodeURIComponent(q));return h?thParse(h):[];}
function thFuzzy(q){var x=thBrowserGet(BASE_URL+'/sitemap-novels.xml');if(!x)return [];var fq=thFold(q),sq=thSlug(q);if(!fq)return [];var toks=fq.split(' '),re=/<url>([\s\S]*?)<\/url>/gi,m,res=[],seen={};while((m=re.exec(x))!==null){var b=m[1],lm=/<loc>([\s\S]*?)<\/loc>/i.exec(b),tm=/<image:title>([\s\S]*?)<\/image:title>/i.exec(b);if(!lm||!tm)continue;var link=thEnt(lm[1]),name=thEnt(tm[1]);if(!link||!name||seen[link])continue;var ft=thFold(name),slug=link.substring(link.lastIndexOf('/')+1).toLowerCase(),all=true,i;for(i=0;i<toks.length;i++){if(toks[i]&&ft.indexOf(toks[i])<0&&slug.indexOf(toks[i])<0){all=false;break;}}if(!all)continue;var score=0;if(ft===fq)score+=10000;if(slug===sq)score+=9500;if(ft.indexOf(fq)>=0)score+=5000;if(slug.indexOf(sq)>=0)score+=4500;score+=Math.max(0,500-Math.abs(ft.length-fq.length)*5);seen[link]=1;res.push({name:name,link:link,cover:'',host:BASE_URL,_s:score});}res.sort(function(a,b){return b._s-a._s||a.name.length-b.name.length;});if(res.length>30)res=res.slice(0,30);for(var j=0;j<res.length;j++)delete res[j]._s;return res;}
function execute(query,page){var p=(page===null||page===undefined||page===''||String(page)==='0')?'1':String(page);if(p!=='1')return Response.success([],null);var q=thNfc(String(query||'').replace(/^\s+|\s+$/g,''));if(!q)return Response.success([],null);var out=thExact(q);if(!out.length)out=thFuzzy(q);return Response.success(out,null);}
