from pathlib import Path
import re

ROOT = Path('cloudflare/runner3-core')
SIMPLE = ROOT / 'artifact-library-simple-entry.js'
V2 = ROOT / 'artifact-library-reader-v2-entry.js'

simple = SIMPLE.read_text(encoding='utf-8')
v2 = V2.read_text(encoding='utf-8')


def replace_once(source: str, old: str, new: str, label: str) -> str:
    count = source.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 match, got {count}')
    return source.replace(old, new, 1)

# Bump client identity so long-lived Reader tabs reload and pick up the UI fix.
simple = replace_once(simple, "reader_client_version:'v65'", "reader_client_version:'v65.1'", 'v65.1 server client version')
simple = replace_once(simple, "'x-r3-reader-client-version':'v65'", "'x-r3-reader-client-version':'v65.1'", 'v65.1 server version header')
v2 = replace_once(v2, "const R3_READER_CLIENT_VERSION_V63='v65';", "const R3_READER_CLIENT_VERSION_V63='v65.1';", 'v65.1 reader client version')

main_runtime = r'''  let r3ManageStateV651={key:'',title:'',busy:false};
  function r3EnsureManageUiV651(){
    let layer=document.getElementById('r3ManageLayerV651');
    if(layer)return layer;
    const style=document.createElement('style');style.id='r3ManageStyleV651';style.textContent=`
.r3-ms-v651{position:fixed;z-index:2147483600;inset:0;display:flex;align-items:flex-end;justify-content:center;padding:12px 12px max(12px,env(safe-area-inset-bottom));background:rgba(0,0,0,.62);backdrop-filter:blur(7px);-webkit-backdrop-filter:blur(7px);opacity:0;pointer-events:none;transition:opacity .16s ease}.r3-ms-v651.open{opacity:1;pointer-events:auto}.r3-ms-v651[hidden]{display:none!important}.r3-ms-card-v651{width:min(520px,100%);max-height:min(72dvh,560px);overflow:auto;background:#11161c;border:1px solid #2a333d;border-radius:22px;box-shadow:0 24px 70px rgba(0,0,0,.55);padding:16px;transform:translateY(18px) scale(.985);transition:transform .18s ease}.r3-ms-v651.open .r3-ms-card-v651{transform:translateY(0) scale(1)}.r3-ms-kicker-v651{font-size:11px;font-weight:850;letter-spacing:.07em;text-transform:uppercase;color:#788696;margin:2px 2px 6px}.r3-ms-title-v651{font-size:17px;line-height:1.28;font-weight:800;color:#f2f6fa;margin:0 2px 14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.r3-ms-actions-v651{display:grid;gap:8px}.r3-ms-btn-v651{width:100%;appearance:none;border:1px solid #2d3742;background:#171e25;color:#eef3f7;border-radius:14px;min-height:52px;padding:0 14px;font:inherit;font-size:15px;font-weight:780;text-align:left}.r3-ms-btn-v651:active{transform:scale(.992);background:#1d2630}.r3-ms-btn-v651.danger{color:#ff6b6b;border-color:rgba(255,107,107,.25);background:rgba(255,107,107,.07)}.r3-ms-btn-v651.primary{text-align:center;background:#eef3f7;color:#0b0f13;border-color:#eef3f7}.r3-ms-btn-v651.cancel{text-align:center;background:transparent;color:#aab5c0}.r3-ms-btn-v651:disabled{opacity:.48}.r3-ms-input-v651{width:100%;appearance:none;border:1px solid #3a4652;background:#0c1116;color:#f3f6f9;border-radius:14px;min-height:50px;padding:11px 13px;font:inherit;font-size:16px;outline:none;margin:0 0 10px}.r3-ms-input-v651:focus{border-color:#8a9bad;box-shadow:0 0 0 3px rgba(138,155,173,.14)}.r3-ms-copy-v651{font-size:13px;line-height:1.45;color:#9aa6b2;margin:0 2px 14px}.r3-ms-error-v651{display:none;color:#ff8989;font-size:12px;line-height:1.4;padding:10px 2px 0}.r3-ms-error-v651.show{display:block}@media(min-width:720px){.r3-ms-v651{align-items:center}.r3-ms-card-v651{border-radius:20px}}`;
    document.head.appendChild(style);
    layer=document.createElement('div');layer.id='r3ManageLayerV651';layer.className='r3-ms-v651';layer.hidden=true;layer.innerHTML=`<section class="r3-ms-card-v651" role="dialog" aria-modal="true" aria-labelledby="r3ManageTitleV651"><div id="r3ManageMenuV651"><div class="r3-ms-kicker-v651">Tùy chọn sách</div><div id="r3ManageTitleV651" class="r3-ms-title-v651"></div><div class="r3-ms-actions-v651"><button id="r3ManageRenameV651" class="r3-ms-btn-v651" type="button">Đổi tên</button><button id="r3ManageDeleteV651" class="r3-ms-btn-v651 danger" type="button">Xóa sách</button><button id="r3ManageCancelV651" class="r3-ms-btn-v651 cancel" type="button">Hủy</button></div></div><div id="r3ManageRenamePanelV651" hidden><div class="r3-ms-kicker-v651">Đổi tên</div><div class="r3-ms-title-v651">Tên sách mới</div><input id="r3ManageRenameInputV651" class="r3-ms-input-v651" maxlength="170" autocomplete="off" autocapitalize="sentences"><div class="r3-ms-actions-v651"><button id="r3ManageRenameSaveV651" class="r3-ms-btn-v651 primary" type="button">Lưu</button><button id="r3ManageRenameBackV651" class="r3-ms-btn-v651 cancel" type="button">Hủy</button></div></div><div id="r3ManageDeletePanelV651" hidden><div class="r3-ms-kicker-v651">Xóa sách</div><div class="r3-ms-title-v651">Xóa khỏi Library?</div><div id="r3ManageDeleteCopyV651" class="r3-ms-copy-v651"></div><div class="r3-ms-actions-v651"><button id="r3ManageDeleteConfirmV651" class="r3-ms-btn-v651 danger" type="button">Xóa sách</button><button id="r3ManageDeleteBackV651" class="r3-ms-btn-v651 cancel" type="button">Hủy</button></div></div><div id="r3ManageErrorV651" class="r3-ms-error-v651" aria-live="polite"></div></section>`;
    document.body.appendChild(layer);
    layer.addEventListener('click',e=>{if(e.target===layer)r3CloseManageV651()});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!layer.hidden)r3CloseManageV651()});
    document.getElementById('r3ManageCancelV651').addEventListener('click',r3CloseManageV651);
    document.getElementById('r3ManageRenameV651').addEventListener('click',r3ShowRenameV651);
    document.getElementById('r3ManageDeleteV651').addEventListener('click',r3ShowDeleteV651);
    document.getElementById('r3ManageRenameBackV651').addEventListener('click',()=>r3ShowManageMenuV651());
    document.getElementById('r3ManageDeleteBackV651').addEventListener('click',()=>r3ShowManageMenuV651());
    document.getElementById('r3ManageRenameSaveV651').addEventListener('click',r3CommitRenameV651);
    document.getElementById('r3ManageDeleteConfirmV651').addEventListener('click',r3CommitDeleteV651);
    document.getElementById('r3ManageRenameInputV651').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();r3CommitRenameV651()}});
    return layer;
  }
  function r3ManageErrorV651(message){const node=document.getElementById('r3ManageErrorV651');if(!node)return;node.textContent=message||'';node.classList.toggle('show',Boolean(message))}
  function r3SetManageBusyV651(busy){r3ManageStateV651.busy=!!busy;for(const id of ['r3ManageRenameSaveV651','r3ManageDeleteConfirmV651','r3ManageRenameBackV651','r3ManageDeleteBackV651']){const node=document.getElementById(id);if(node)node.disabled=!!busy}const save=document.getElementById('r3ManageRenameSaveV651'),del=document.getElementById('r3ManageDeleteConfirmV651');if(save)save.textContent=busy?'Đang lưu…':'Lưu';if(del)del.textContent=busy?'Đang xóa…':'Xóa sách'}
  function r3ShowManageMenuV651(){r3ManageErrorV651('');document.getElementById('r3ManageMenuV651').hidden=false;document.getElementById('r3ManageRenamePanelV651').hidden=true;document.getElementById('r3ManageDeletePanelV651').hidden=true;document.getElementById('r3ManageTitleV651').textContent=r3ManageStateV651.title||'Sách'}
  function r3ShowRenameV651(){r3ManageErrorV651('');document.getElementById('r3ManageMenuV651').hidden=true;document.getElementById('r3ManageRenamePanelV651').hidden=false;document.getElementById('r3ManageDeletePanelV651').hidden=true;const input=document.getElementById('r3ManageRenameInputV651');input.value=r3ManageStateV651.title||'';setTimeout(()=>{input.focus();input.setSelectionRange(0,input.value.length)},40)}
  function r3ShowDeleteV651(){r3ManageErrorV651('');document.getElementById('r3ManageMenuV651').hidden=true;document.getElementById('r3ManageRenamePanelV651').hidden=true;document.getElementById('r3ManageDeletePanelV651').hidden=false;document.getElementById('r3ManageDeleteCopyV651').textContent='Sách “'+(r3ManageStateV651.title||'này')+'” sẽ bị xóa khỏi Library. Hành động này không thể hoàn tác.'}
  function r3OpenManageV651(bookKey,title){const layer=r3EnsureManageUiV651();r3ManageStateV651={key:String(bookKey||''),title:String(title||'').trim()||'Sách',busy:false};r3SetManageBusyV651(false);r3ShowManageMenuV651();layer.hidden=false;requestAnimationFrame(()=>layer.classList.add('open'))}
  function r3CloseManageV651(){const layer=document.getElementById('r3ManageLayerV651');if(!layer||r3ManageStateV651.busy)return;layer.classList.remove('open');setTimeout(()=>{layer.hidden=true},170)}
  async function r3CommitRenameV651(){if(r3ManageStateV651.busy)return;const input=document.getElementById('r3ManageRenameInputV651');const name=String(input?.value||'').trim();if(!name){r3ManageErrorV651('Tên sách không được để trống.');return}if(name===r3ManageStateV651.title){r3CloseManageV651();return}r3SetManageBusyV651(true);r3ManageErrorV651('');try{const response=await fetch('/artifact-library/api/manage',{method:'POST',headers:{'content-type':'application/json','x-runner3-library':'1'},body:JSON.stringify({action:'rename',key:r3ManageStateV651.key,name})});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok!==true)throw new Error(data.error==='EPUB_RENAME_COLLISION'?'Tên này đã tồn tại.':(data.error||('HTTP '+response.status)));r3MigrateLocalBookKeyV65(r3ManageStateV651.key,data.new_key||r3ManageStateV651.key);r3ManageStateV651.busy=false;const layer=document.getElementById('r3ManageLayerV651');if(layer){layer.classList.remove('open');layer.hidden=true}status('Đã đổi tên.');await load()}catch(error){r3SetManageBusyV651(false);r3ManageErrorV651(String(error&&error.message||error))}}
  async function r3CommitDeleteV651(){if(r3ManageStateV651.busy)return;r3SetManageBusyV651(true);r3ManageErrorV651('');try{const bookKey=r3ManageStateV651.key;const response=await fetch('/artifact-library/api/manage',{method:'POST',headers:{'content-type':'application/json','x-runner3-library':'1'},body:JSON.stringify({action:'delete',key:bookKey})});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok!==true)throw new Error(data.error||('HTTP '+response.status));try{localStorage.removeItem(PROGRESS_PREFIX+bookKey);localStorage.removeItem(POSITION_PREFIX+bookKey)}catch{}r3ManageStateV651.busy=false;const layer=document.getElementById('r3ManageLayerV651');if(layer){layer.classList.remove('open');layer.hidden=true}status('Đã xóa.');await load()}catch(error){r3SetManageBusyV651(false);r3ManageErrorV651(String(error&&error.message||error))}}
  async function r3ManageBookV65(bookKey,title){r3OpenManageV651(bookKey,title)}
'''

main_pattern=re.compile(r"  async function r3ManageBookV65\(bookKey,title\)\{.*?\n(?=  function r3InstallMainManageV65\(\))",re.S)
simple,count=main_pattern.subn(main_runtime,simple,count=1)
if count!=1: raise SystemExit(f'v65.1 main manage replacement: expected 1 match, got {count}')
# Make the ellipsis control visually lighter; the bottom sheet now carries the hierarchy.
simple=simple.replace(".r3-manage-v65{appearance:none;border:0;border-left:1px solid #202832;background:#111820;color:#aeb9c6;width:42px;display:grid;place-items:center;padding:0;font:inherit;font-size:20px;font-weight:900;cursor:pointer}",".r3-manage-v65{appearance:none;border:0;background:transparent;color:#93a0ad;width:42px;display:grid;place-items:center;padding:0;font:inherit;font-size:20px;font-weight:900;cursor:pointer}.r3-manage-v65:active{background:#182028}",1)
simple=simple.replace("button.setAttribute('aria-label','Rename hoặc Delete')","button.setAttribute('aria-label','Tùy chọn sách')",1)

reader_runtime = r'''  let r3ReaderManageStateV651={key:'',title:'',busy:false};
  function r3EnsureReaderManageUiV651(){
    let layer=document.getElementById('r3ReaderManageLayerV651');if(layer)return layer;
    const style=document.createElement('style');style.id='r3ReaderManageStyleV651';style.textContent=`
.r3-rms-v651{position:fixed;z-index:2147483640;inset:0;display:flex;align-items:flex-end;justify-content:center;padding:12px 12px max(12px,env(safe-area-inset-bottom));background:rgba(0,0,0,.62);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);opacity:0;pointer-events:none;transition:opacity .16s ease}.r3-rms-v651.open{opacity:1;pointer-events:auto}.r3-rms-v651[hidden]{display:none!important}.r3-rms-card-v651{width:min(520px,100%);max-height:min(72dvh,560px);overflow:auto;background:#11161c;color:#f2f6fa;border:1px solid #2b343e;border-radius:22px;box-shadow:0 24px 70px rgba(0,0,0,.58);padding:16px;transform:translateY(18px) scale(.985);transition:transform .18s ease}.r3-rms-v651.open .r3-rms-card-v651{transform:translateY(0) scale(1)}.r3-rms-kicker-v651{font-size:11px;font-weight:850;letter-spacing:.07em;text-transform:uppercase;color:#7c8996;margin:2px 2px 6px}.r3-rms-title-v651{font-size:17px;line-height:1.28;font-weight:800;margin:0 2px 14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.r3-rms-actions-v651{display:grid;gap:8px}.r3-rms-btn-v651{width:100%;appearance:none;border:1px solid #2e3843;background:#171e25;color:#eef3f7;border-radius:14px;min-height:52px;padding:0 14px;font:inherit;font-size:15px;font-weight:780;text-align:left}.r3-rms-btn-v651:active{transform:scale(.992);background:#1d2630}.r3-rms-btn-v651.danger{color:#ff6b6b;border-color:rgba(255,107,107,.25);background:rgba(255,107,107,.07)}.r3-rms-btn-v651.primary{text-align:center;background:#eef3f7;color:#0b0f13;border-color:#eef3f7}.r3-rms-btn-v651.cancel{text-align:center;background:transparent;color:#aab5c0}.r3-rms-btn-v651:disabled{opacity:.48}.r3-rms-input-v651{width:100%;appearance:none;border:1px solid #3a4652;background:#0c1116;color:#f3f6f9;border-radius:14px;min-height:50px;padding:11px 13px;font:inherit;font-size:16px;outline:none;margin:0 0 10px}.r3-rms-input-v651:focus{border-color:#8a9bad;box-shadow:0 0 0 3px rgba(138,155,173,.14)}.r3-rms-copy-v651{font-size:13px;line-height:1.45;color:#9aa6b2;margin:0 2px 14px}.r3-rms-error-v651{display:none;color:#ff8989;font-size:12px;line-height:1.4;padding:10px 2px 0}.r3-rms-error-v651.show{display:block}.r3-live-manage-v65{border:0!important;background:transparent!important;color:var(--muted)!important;min-width:40px!important;width:40px!important;height:40px!important;padding:0!important;margin-left:2px!important;border-radius:11px!important}.r3-live-manage-v65:active{background:rgba(127,139,152,.12)!important}@media(min-width:720px){.r3-rms-v651{align-items:center}.r3-rms-card-v651{border-radius:20px}}`;
    document.head.appendChild(style);
    layer=document.createElement('div');layer.id='r3ReaderManageLayerV651';layer.className='r3-rms-v651';layer.hidden=true;layer.innerHTML=`<section class="r3-rms-card-v651" role="dialog" aria-modal="true" aria-labelledby="r3ReaderManageTitleV651"><div id="r3ReaderManageMenuV651"><div class="r3-rms-kicker-v651">Tùy chọn sách</div><div id="r3ReaderManageTitleV651" class="r3-rms-title-v651"></div><div class="r3-rms-actions-v651"><button id="r3ReaderManageRenameV651" class="r3-rms-btn-v651" type="button">Đổi tên</button><button id="r3ReaderManageDeleteV651" class="r3-rms-btn-v651 danger" type="button">Xóa sách</button><button id="r3ReaderManageCancelV651" class="r3-rms-btn-v651 cancel" type="button">Hủy</button></div></div><div id="r3ReaderManageRenamePanelV651" hidden><div class="r3-rms-kicker-v651">Đổi tên</div><div class="r3-rms-title-v651">Tên sách mới</div><input id="r3ReaderManageRenameInputV651" class="r3-rms-input-v651" maxlength="170" autocomplete="off" autocapitalize="sentences"><div class="r3-rms-actions-v651"><button id="r3ReaderManageRenameSaveV651" class="r3-rms-btn-v651 primary" type="button">Lưu</button><button id="r3ReaderManageRenameBackV651" class="r3-rms-btn-v651 cancel" type="button">Hủy</button></div></div><div id="r3ReaderManageDeletePanelV651" hidden><div class="r3-rms-kicker-v651">Xóa sách</div><div class="r3-rms-title-v651">Xóa khỏi Library?</div><div id="r3ReaderManageDeleteCopyV651" class="r3-rms-copy-v651"></div><div class="r3-rms-actions-v651"><button id="r3ReaderManageDeleteConfirmV651" class="r3-rms-btn-v651 danger" type="button">Xóa sách</button><button id="r3ReaderManageDeleteBackV651" class="r3-rms-btn-v651 cancel" type="button">Hủy</button></div></div><div id="r3ReaderManageErrorV651" class="r3-rms-error-v651" aria-live="polite"></div></section>`;
    document.body.appendChild(layer);
    layer.addEventListener('click',e=>{if(e.target===layer)r3CloseReaderManageV651()});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!layer.hidden)r3CloseReaderManageV651()});
    document.getElementById('r3ReaderManageCancelV651').addEventListener('click',r3CloseReaderManageV651);
    document.getElementById('r3ReaderManageRenameV651').addEventListener('click',r3ShowReaderRenameV651);
    document.getElementById('r3ReaderManageDeleteV651').addEventListener('click',r3ShowReaderDeleteV651);
    document.getElementById('r3ReaderManageRenameBackV651').addEventListener('click',r3ShowReaderMenuV651);
    document.getElementById('r3ReaderManageDeleteBackV651').addEventListener('click',r3ShowReaderMenuV651);
    document.getElementById('r3ReaderManageRenameSaveV651').addEventListener('click',r3CommitReaderRenameV651);
    document.getElementById('r3ReaderManageDeleteConfirmV651').addEventListener('click',r3CommitReaderDeleteV651);
    document.getElementById('r3ReaderManageRenameInputV651').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();r3CommitReaderRenameV651()}});
    return layer;
  }
  function r3ReaderManageErrorV651(message){const node=document.getElementById('r3ReaderManageErrorV651');if(!node)return;node.textContent=message||'';node.classList.toggle('show',Boolean(message))}
  function r3SetReaderManageBusyV651(busy){r3ReaderManageStateV651.busy=!!busy;for(const id of ['r3ReaderManageRenameSaveV651','r3ReaderManageDeleteConfirmV651','r3ReaderManageRenameBackV651','r3ReaderManageDeleteBackV651']){const node=document.getElementById(id);if(node)node.disabled=!!busy}const save=document.getElementById('r3ReaderManageRenameSaveV651'),del=document.getElementById('r3ReaderManageDeleteConfirmV651');if(save)save.textContent=busy?'Đang lưu…':'Lưu';if(del)del.textContent=busy?'Đang xóa…':'Xóa sách'}
  function r3ShowReaderMenuV651(){r3ReaderManageErrorV651('');document.getElementById('r3ReaderManageMenuV651').hidden=false;document.getElementById('r3ReaderManageRenamePanelV651').hidden=true;document.getElementById('r3ReaderManageDeletePanelV651').hidden=true;document.getElementById('r3ReaderManageTitleV651').textContent=r3ReaderManageStateV651.title||'Sách'}
  function r3ShowReaderRenameV651(){r3ReaderManageErrorV651('');document.getElementById('r3ReaderManageMenuV651').hidden=true;document.getElementById('r3ReaderManageRenamePanelV651').hidden=false;document.getElementById('r3ReaderManageDeletePanelV651').hidden=true;const input=document.getElementById('r3ReaderManageRenameInputV651');input.value=r3ReaderManageStateV651.title||'';setTimeout(()=>{input.focus();input.setSelectionRange(0,input.value.length)},40)}
  function r3ShowReaderDeleteV651(){r3ReaderManageErrorV651('');document.getElementById('r3ReaderManageMenuV651').hidden=true;document.getElementById('r3ReaderManageRenamePanelV651').hidden=true;document.getElementById('r3ReaderManageDeletePanelV651').hidden=false;document.getElementById('r3ReaderManageDeleteCopyV651').textContent='Sách “'+(r3ReaderManageStateV651.title||'này')+'” sẽ bị xóa khỏi Library. Hành động này không thể hoàn tác.'}
  function r3OpenReaderManageV651(bookKey,title){const layer=r3EnsureReaderManageUiV651();r3ReaderManageStateV651={key:String(bookKey||''),title:String(title||'').trim()||'Sách',busy:false};r3SetReaderManageBusyV651(false);r3ShowReaderMenuV651();layer.hidden=false;requestAnimationFrame(()=>layer.classList.add('open'))}
  function r3CloseReaderManageV651(){const layer=document.getElementById('r3ReaderManageLayerV651');if(!layer||r3ReaderManageStateV651.busy)return;layer.classList.remove('open');setTimeout(()=>{layer.hidden=true},170)}
  async function r3CommitReaderRenameV651(){if(r3ReaderManageStateV651.busy)return;const input=document.getElementById('r3ReaderManageRenameInputV651');const name=String(input?.value||'').trim();if(!name){r3ReaderManageErrorV651('Tên sách không được để trống.');return}if(name===r3ReaderManageStateV651.title){r3CloseReaderManageV651();return}r3SetReaderManageBusyV651(true);r3ReaderManageErrorV651('');try{const bookKey=r3ReaderManageStateV651.key;const response=await fetch('/artifact-library/api/manage',{method:'POST',headers:{'content-type':'application/json','x-runner3-library':'1'},body:JSON.stringify({action:'rename',key:bookKey,name})});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok!==true)throw new Error(data.error==='EPUB_RENAME_COLLISION'?'Tên này đã tồn tại.':(data.error||('HTTP '+response.status)));r3MigrateReaderLocalKeyV65(bookKey,data.new_key||bookKey);r3ReaderManageStateV651.busy=false;if(bookKey===key){location.replace('/artifact-library/read?key='+encodeURIComponent(data.new_key));return}location.reload()}catch(error){r3SetReaderManageBusyV651(false);r3ReaderManageErrorV651(String(error&&error.message||error))}}
  async function r3CommitReaderDeleteV651(){if(r3ReaderManageStateV651.busy)return;r3SetReaderManageBusyV651(true);r3ReaderManageErrorV651('');try{const bookKey=r3ReaderManageStateV651.key;const response=await fetch('/artifact-library/api/manage',{method:'POST',headers:{'content-type':'application/json','x-runner3-library':'1'},body:JSON.stringify({action:'delete',key:bookKey})});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok!==true)throw new Error(data.error||('HTTP '+response.status));try{localStorage.removeItem(R3_READER_PROGRESS_PREFIX_V54+bookKey);localStorage.removeItem('r3-reader-position:'+bookKey)}catch{}r3ReaderManageStateV651.busy=false;if(bookKey===key){location.replace('/artifact-library');return}location.reload()}catch(error){r3SetReaderManageBusyV651(false);r3ReaderManageErrorV651(String(error&&error.message||error))}}
  async function r3ReaderManageBookV65(bookKey,title){r3OpenReaderManageV651(bookKey,title)}
'''

reader_pattern=re.compile(r"  async function r3ReaderManageBookV65\(bookKey,title\)\{.*?\n(?=  function r3InstallLiveManageV65\(\))",re.S)
v2,count=reader_pattern.subn(reader_runtime,v2,count=1)
if count!=1: raise SystemExit(f'v65.1 reader manage replacement: expected 1 match, got {count}')
v2=v2.replace("button.setAttribute('aria-label','Rename hoặc Delete')","button.setAttribute('aria-label','Tùy chọn sách')",1)

for marker in ["reader_client_version:'v65.1'",'r3ManageLayerV651','r3CommitRenameV651','r3CommitDeleteV651','Đổi tên','Xóa sách']:
    if marker not in simple: raise SystemExit('V651_SIMPLE_MISSING:'+marker)
for marker in ["R3_READER_CLIENT_VERSION_V63='v65.1'",'r3ReaderManageLayerV651','r3CommitReaderRenameV651','r3CommitReaderDeleteV651','.r3-live-manage-v65{border:0!important']:
    if marker not in v2: raise SystemExit('V651_READER_MISSING:'+marker)
if "prompt('R = Rename" in simple or "confirm('Xóa sách này" in simple: raise SystemExit('V651_SIMPLE_NATIVE_DIALOG_REMAINS')
if "prompt('R = Rename" in v2 or "confirm('Xóa sách này" in v2: raise SystemExit('V651_READER_NATIVE_DIALOG_REMAINS')

SIMPLE.write_text(simple,encoding='utf-8')
V2.write_text(v2,encoding='utf-8')
print('READER_V65_1_MANAGE_SHEET=PASS')
