import { r3StableEarlyV82 } from '../cloudflare/runner3-core/artifact-library-reader-v82-stable-shell-entry.js';
const realSetTimeout=globalThis.setTimeout;
const realSetInterval=globalThis.setInterval;
const realAddEventListener=globalThis.addEventListener;
const classes=new Set();
const classList={add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x)};
globalThis.window=globalThis;
Object.defineProperty(globalThis,'navigator',{value:{standalone:false},configurable:true});
globalThis.document={documentElement:{classList}};
globalThis.matchMedia=()=>({matches:false});
globalThis.addEventListener=()=>{};
globalThis.setTimeout=(fn,ms,...args)=>realSetTimeout(fn,Math.min(Number(ms)||0,5),...args);
globalThis.setInterval=(fn,ms,...args)=>realSetInterval(fn,Math.max(1000,Number(ms)||1000),...args);
r3StableEarlyV82();
if(classes.has('r3-v82-restoring'))throw new Error('blocking restore shield was armed');
if(globalThis.__r3StableEarlyV82?.restoreGuard!=='nonblocking-v89')throw new Error('nonblocking v89 guard missing');
classes.add('r3-restore-pending-v45');
globalThis.__r3StableEarlyV82.releaseRestoreShield('smoke-release');
await new Promise(r=>realSetTimeout(r,30));
if(classes.has('r3-v82-restoring')||classes.has('r3-restore-pending-v45'))throw new Error('restore classes did not release');
globalThis.setTimeout=realSetTimeout;
globalThis.setInterval=realSetInterval;
if(realAddEventListener===undefined)delete globalThis.addEventListener;else globalThis.addEventListener=realAddEventListener;
console.log('READER_V88_RESTORE_FAILSAFE_SMOKE=PASS nonblocking=v89');
