const mod=await import('../cloudflare/runner3-core/artifact-library-reader-v82-stable-shell-entry.js?cleanv112='+Date.now());
const key='core/ebook/smoke/final/Smoke.epub';
const env={ARTIFACTS:{head:async value=>value===key?{key:value}:null}};
const iphone='Mozilla/5.0 (iPhone; CPU iPhone OS 26_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 Mobile/15E148 Safari/604.1';
const req=new Request('https://example.test/artifact-library/read?key='+encodeURIComponent(key),{headers:{'user-agent':iphone}});
const res=await mod.default.fetch(req,env,{});const html=await res.text();
if(res.status!==200)throw new Error('clean ios status '+res.status+': '+html.slice(0,180));
if(res.headers.get('x-r3-reader-ios-clean')!=='v120')throw new Error('clean ios header missing');
if(res.headers.get('x-r3-reader-legacy-chain')!=='bypassed-v120')throw new Error('legacy bypass header missing');
for(const marker of ['data-r3-clean-ios-v112="1"','data-r3-clean-ios-runtime-v112="1"','data-r3-physical-trace-v113="1"','reader-clean-ios-v112','id="viewer"'])if(!html.includes(marker))throw new Error('clean marker missing '+marker);
for(const forbidden of ['data-r3-audio-continuity-v35="1"','data-r3-audio-continuity-v34="1"','data-r3-stable-shell-runtime-v82="1"','data-r3-ebook-audio-v6="2"'])if(html.includes(forbidden))throw new Error('legacy marker leaked '+forbidden);
for(const heavy of ['book.locations.generate(1600)','setInterval(runColdBootGuardV62,100)',"owner:'safari-boot-geometry-v61'"])if(html.includes(heavy))throw new Error('heavy ios boot leaked '+heavy);
for(const marker of ["owner:'minimal-ios-v112'","reason:'large-book-main-thread'",'window.__r3IosMinimalBootV112'])if(!html.includes(marker))throw new Error('minimal boot marker missing '+marker);
const csp=String(res.headers.get('content-security-policy')||'');if(!/connect-src[^;]*\bblob:/.test(csp)||!/style-src[^;]*\bblob:/.test(csp)||!/base-uri\s+'self'/.test(csp))throw new Error('clean CSP v111 missing '+csp);
if(!html.includes("rendition.hooks.content.register"))throw new Error('v116 content hook missing');
if(!html.includes("frame.hook.bound"))throw new Error('v116 frame trace missing');
if(html.includes(".chrome{opacity:1!important}"))throw new Error('v116 chrome must auto-hide');
if(!html.includes("center-toggle-v120"))throw new Error('v120 center-toggle gesture missing');
if(!html.includes('__r3IosPageNextV117')||!html.includes('nav.edge.done')||!html.includes("r3DirectPageV117('next')"))throw new Error('v120 edge navigation owner missing');
if(!html.includes('.topbar{top:28px!important}')||!html.includes('top:max(44px,calc(env(safe-area-inset-top,0px) + 16px))')||!html.includes('width:28vw')||!html.includes('opacity:0!important')||!html.includes('bottom:calc(132px + env(safe-area-inset-bottom,0px))'))throw new Error('v120 product geometry missing');
if(!html.includes('__r3CleanAudioFollowV120')||!html.includes('r3-audio-follow-v120')||!html.includes('sentenceRange(index)')||!html.includes('audio.timing.ready')||!html.includes('setTimeout(runFollowLoop,90)'))throw new Error('v120 event-driven audio follow missing');
if(html.includes('setInterval(runFollowLoop'))throw new Error('v120 idle audio polling leaked');
if(html.includes('nav.direct.done'))throw new Error('v120 old visible-nav telemetry leaked');
if(!html.includes("scheduleSettingsIdleClose"))throw new Error('v116 settings idle close missing');
if(!html.includes("prevButton.id='r3CleanPrev'")||!html.includes("nextButton.id='r3CleanNext'"))throw new Error('v116 top nav missing');
const desktop=new Request('https://example.test/artifact-library/read?key='+encodeURIComponent(key),{headers:{'user-agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/140 Safari/537.36'}});
const dres=await mod.default.fetch(desktop,env,{});const dhtml=await dres.text();
if(dres.status!==200||dres.headers.get('x-r3-reader-stable-shell')!=='v82')throw new Error('desktop legacy fallback broken '+dres.status);
if(dres.headers.get('x-r3-reader-ios-clean'))throw new Error('desktop incorrectly clean');
if(!dhtml.includes('data-r3-stable-shell-runtime-v82="1"'))throw new Error('desktop stable shell missing');
console.log('READER_V112_MINIMAL_IOS_SMOKE=PASS iosBytes='+html.length+' desktopBytes='+dhtml.length);
