import crypto from 'node:crypto';
import { webkit } from 'playwright';
const token=String(process.env.RUNNER3_CORE_TOKEN||'').trim();if(!token)throw new Error('RUNNER3_CORE_TOKEN_MISSING');
const core=String(process.env.RUNNER3_CORE_URL||'https://runner3-core.ducduy2411.workers.dev').replace(/\/$/,'');
const bookKey=String(process.env.EBOOK_WEBKIT_BOOK_KEY||'core/ebook/tha-nu-phu-thuy-kia-ra-nhi-muc-1lwhn39/final/Thả Nữ Phù Thủy Kia Ra - Nhị Mục.epub');
const cookieValue=crypto.createHash('sha256').update('runner3-artifact-library-v1:'+token).digest('hex');const host=new URL(core).hostname;
const iphone='Mozilla/5.0 (iPhone; CPU iPhone OS 26_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/153.0.8010.24 Mobile/15E148 Safari/604.1';
const browser=await webkit.launch({headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,userAgent:iphone});
await context.addCookies([{name:'r3_artifact_library',value:cookieValue,domain:host,path:'/artifact-library',httpOnly:true,secure:true,sameSite:'Lax'}]);
await context.route('**/artifact-library/api/progress**',async route=>{if(route.request().method()==='POST')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,items:[],smoke:true})});return route.continue();});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e?.stack||e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const url=core+'/artifact-library/read?key='+encodeURIComponent(bookKey);
try{
 let response=null;for(let attempt=1;attempt<=20;attempt++){response=await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});if(response?.status()===200&&response.headers()['x-r3-reader-ios-clean']==='v121')break;if(attempt===20)throw new Error('V112_NOT_LIVE '+JSON.stringify({status:response?.status(),headers:response?.headers()}));await page.waitForTimeout(1000)}
 if(response.headers()['x-r3-reader-legacy-chain']!=='bypassed-v121')throw new Error('V112_LEGACY_NOT_BYPASSED');
 await page.waitForFunction(()=>window.__R3_BASE_READER_BOOT_DONE===true,null,{timeout:30000});
 await page.waitForSelector('#viewer iframe',{timeout:30000});
 await page.waitForFunction(()=>{const f=document.querySelector('#viewer iframe');try{return String(f?.contentDocument?.body?.innerText||'').trim().length>80}catch{return false}},null,{timeout:30000});
 const state=await page.evaluate(()=>({clean:document.documentElement.dataset.r3CleanIos||'',debug:window.__r3CleanIosV112||null,boot:window.__r3IosMinimalBootV112||null,locations:window.__r3IosLocationsV112||null,legacy35:Boolean(document.querySelector('script[data-r3-audio-continuity-v35]')),legacy82:Boolean(document.querySelector('script[data-r3-stable-shell-runtime-v82]')),frameText:String(document.querySelector('#viewer iframe')?.contentDocument?.body?.innerText||'').trim().length,controls:document.body.classList.contains('controls')}));
 if(state.clean!=='v112'||state.legacy35||state.legacy82||state.frameText<80||state.boot?.phase!=='done'||state.locations?.disabled!==true)throw new Error('V112_BAD_RUNTIME '+JSON.stringify(state));
 await page.waitForFunction(()=>{const f=document.querySelector('#viewer iframe');try{return f?.contentDocument?.documentElement?.dataset?.r3IosGesture==='center-toggle-v121'}catch{return false}},null,{timeout:8000});
 const settings=page.locator('#settingsButton');await settings.waitFor({state:'visible',timeout:10000});const settingsBox=await settings.boundingBox();if(!settingsBox||settingsBox.y<36)throw new Error('V120_TOPBAR_TOO_HIGH '+JSON.stringify(settingsBox));const viewerBox=await page.locator('#viewer').boundingBox();if(!viewerBox||viewerBox.y<40)throw new Error('V120_READING_TOP_INSET_TOO_SMALL '+JSON.stringify(viewerBox));await settings.click({timeout:10000});await page.waitForFunction(()=>document.body.classList.contains('settings'),null,{timeout:5000});await page.waitForFunction(()=>{const el=document.getElementById('settingsSheet'),cs=el&&getComputedStyle(el);return Boolean(el&&Number(cs.opacity)>.9&&cs.pointerEvents!=='none')},null,{timeout:3000});const sheetState=await page.locator('#settingsSheet').evaluate(el=>{const r=el.getBoundingClientRect(),cs=getComputedStyle(el);return {w:r.width,h:r.height,opacity:Number(cs.opacity),pointer:cs.pointerEvents}});if(sheetState.w<100||sheetState.h<100||sheetState.opacity<.9||sheetState.pointer==='none')throw new Error('V118_SETTINGS_NOT_VISIBLE '+JSON.stringify(sheetState));await page.locator('#closeSettings').click({timeout:10000});await page.waitForFunction(()=>!document.body.classList.contains('settings'),null,{timeout:5000});await settings.click({timeout:10000});await page.waitForFunction(()=>document.body.classList.contains('settings'),null,{timeout:5000});await page.waitForFunction(()=>!document.body.classList.contains('settings'),null,{timeout:8000});
 await page.waitForFunction(()=>{const f=document.querySelector('#viewer iframe');try{return f?.contentDocument?.documentElement?.dataset?.r3GestureV2==='1'}catch{return false}},null,{timeout:8000});
 const expand=page.locator('#r3CleanExpand');await expand.click({timeout:10000});await page.waitForFunction(()=>document.getElementById('r3CleanAudio')?.classList.contains('r3-expanded'),null,{timeout:5000});
 const speed=page.locator('#r3CleanSpeed');const speedBefore=String(await speed.textContent()||'');await speed.click({timeout:10000});const speedAfter=String(await speed.textContent()||'');if(speedAfter===speedBefore)throw new Error('V112_SPEED_DEAD');
 const positionKey='r3-reader-position:'+bookKey;const zone=await page.locator('#r3CleanNext').evaluate(el=>{const r=el.getBoundingClientRect(),cs=getComputedStyle(el);return {x:r.x,y:r.y,w:r.width,h:r.height,opacity:Number(cs.opacity),bg:cs.backgroundColor}});if(zone.w<95||zone.w>150||zone.h<400||zone.opacity!==0)throw new Error('V121_EDGE_ZONE_BAD '+JSON.stringify(zone));await page.evaluate(()=>document.body.classList.remove('controls'));await page.waitForTimeout(850);let frame=null;for(const candidate of page.frames()){if(candidate===page.mainFrame())continue;try{if(await candidate.evaluate(()=>document.documentElement?.dataset?.r3IosGesture==='center-toggle-v121')){frame=candidate;break}}catch{}}if(!frame)throw new Error('V121_FRAME_MISSING');await frame.evaluate(()=>{const x=innerWidth/2,y=Math.max(40,innerHeight/2),el=document.elementFromPoint(x,y)||document.body;el.dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:x,clientY:y}))});await page.waitForFunction(()=>document.body.classList.contains('controls'),null,{timeout:3000});await page.evaluate(()=>document.body.classList.remove('controls'));const before=await page.evaluate(k=>String(localStorage.getItem(k)||''),positionKey);await page.mouse.click(375,400);await page.waitForFunction(({k,b})=>{const n=String(localStorage.getItem(k)||'');return Boolean(n&&n!==b)},{k:positionKey,b:before},{timeout:8000});await page.waitForFunction(()=>!document.body.classList.contains('controls'),null,{timeout:3000});const after=await page.evaluate(k=>String(localStorage.getItem(k)||''),positionKey);if(!after||after===before)throw new Error('V121_EDGE_NAV_DEAD');
 const followProof=await page.evaluate(async()=>{const fs=[...document.querySelectorAll('#viewer iframe')];let f=null,best=-1;for(const x of fs){try{const n=String(x.contentDocument?.body?.innerText||'').length;if(n>best){best=n;f=x}}catch{}}const d=f&&f.contentDocument,dbg=window.__r3CleanAudioFollowV120;if(!d||!dbg)return {mapped:0,highlight:false};const raw=String(d.body?.innerText||'');const toks=raw.match(/[\p{L}\p{M}\p{N}]+/gu)?.slice(0,12)||[];const words=toks.map((text,i)=>({text,startMs:i*120}));const mapped=dbg.installTestTiming(words);await dbg.syncTest(360);let highlight=false;try{highlight=!!d.defaultView?.CSS?.highlights?.has('r3-audio-follow-v120')}catch{}return {mapped,highlight,lastIndex:dbg.lastIndex}});if(followProof.mapped<3||!followProof.highlight)throw new Error('V120_AUDIO_FOLLOW_DEAD '+JSON.stringify(followProof));
 if(errors.length)throw new Error('V112_CONSOLE_ERRORS '+JSON.stringify(errors.slice(0,8)));
 console.log(JSON.stringify({ok:true,mode:'iphone-product-spec-v121',frameText:state.frameText,settings:true,audioControls:{expand:true,speedBefore,speedAfter},navigation:{cfiChanged:true},legacyBypassed:true,minimalBoot:{totalMs:state.boot?.totalMs||0,fetchMs:state.boot?.fetchMs||0,displayMs:state.boot?.displayMs||0},locationsDisabled:state.locations?.disabled===true}));
}finally{await browser.close()}
