import { r3StableEarlyV82 } from '../cloudflare/runner3-core/artifact-library-reader-v82-stable-shell-entry.js';
const realSetTimeout=globalThis.setTimeout;
const realSetInterval=globalThis.setInterval;
const realAddEventListener=globalThis.addEventListener;
const classes=new Set();
const classList={add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x)};
globalThis.window=globalThis;
Object.defineProperty(globalThis,'navigator',{value:{standalone:false},configurable:true});
globalThis.document={documentElement:{classList}};
globalThis.matchMedia=()=>({matches:false});
globalThis.addEventListener=()=>{};
globalThis.setTimeout=(fn,ms,...args)=>realSetTimeout(fn,Math.min(Number(ms)||0,5),...args);
globalThis.setInterval=(fn,ms,...args)=>realSetInterval(fn,Math.max(1000,Number(ms)||1000),...args);
r3StableEarlyV82();
if(!classes.has('r3-v82-restoring'))throw new Error('restore shield was not armed');
await new Promise(r=>realSetTimeout(r,30));
if(classes.has('r3-v82-restoring')||classes.has('r3-restore-pending-v45'))throw new Error('restore shield watchdog did not release');
if(!globalThis.__r3StableEarlyV82?.restoreWatchdogFired)throw new Error('watchdog proof missing');
if(globalThis.__r3StableEarlyV82?.restoreGuard!=='fail-safe-v88')throw new Error('v88 restore guard missing');
globalThis.setTimeout=realSetTimeout;
globalThis.setInterval=realSetInterval;
if(realAddEventListener===undefined)delete globalThis.addEventListener;else globalThis.addEventListener=realAddEventListener;
console.log('READER_V88_RESTORE_FAILSAFE_SMOKE=PASS');
