load('transport.js');
var BASE_URL='https://truyenhub.net';
function thAbs(h){h=String(h||'');if(!h)return '';if(h.indexOf('http://')===0||h.indexOf('https://')===0)return h;if(h.charAt(0)!='/')h='/'+h;return BASE_URL+h;}
function thName(e){var n='';try{n=e.attr('title')||'';}catch(x){}if(!n){try{var im=e.select('img');if(im&&im.size()>0)n=im.get(0).attr('alt')||'';}catch(y){}}if(!n){try{n=e.text()||'';}catch(z){}}n=String(n||'').replace(/^Bìa truyện\s+/i,'').replace(/^\s+|\s+$/g,'');if(n==='Đọc ngay'||n==='Đọc tiếp'||n==='Xem truyện')n='';return n;}
function thList(d){var out=[],seen={};if(!d||!d.select)return out;var es=null;try{es=d.select('h1 a[href*="/truyen/"],h2 a[href*="/truyen/"],h3 a[href*="/truyen/"],h4 a[href*="/truyen/"],a[title][href*="/truyen/"],a[href*="/truyen/"]');}catch(e){return out;}for(var i=0;i<es.size();i++){var e=es.get(i),h=thAbs(e.attr('href')||'');if(!h||h.indexOf(BASE_URL+'/truyen/')!==0||h.indexOf('/chuong-')>=0||seen[h])continue;var n=thName(e);if(!n)continue;var cover='';try{var ims=e.select('img');if(ims.size()>0){var im=ims.get(0);cover=im.attr('data-src')||im.attr('data-lazy-src')||im.attr('src')||'';}}catch(x){}seen[h]=1;out.push({name:n,link:h,cover:thAbs(cover),host:BASE_URL});}return out;}
function thNfc(s){s=String(s||'');try{if(s.normalize)s=s.normalize('NFC');}catch(e){}return s;}
function thFold(s){s=thNfc(s).toLowerCase();try{if(s.normalize)s=s.normalize('NFD');}catch(e){}s=s.replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');return s.replace(/[^a-z0-9]+/g,' ').replace(/^\s+|\s+$/g,'').replace(/\s+/g,' ');}
function thMatch(a,q){var fq=thFold(q),fn=thFold(a.name||'');if(!fq||!fn)return false;if(fn===fq||fn.indexOf(fq)>=0||fq.indexOf(fn)>=0)return true;var toks=fq.split(' ');for(var i=0;i<toks.length;i++)if(toks[i]&&fn.indexOf(toks[i])<0)return false;return true;}
function execute(query,page){var p=(page===null||page===undefined||page===''||String(page)==='0')?'1':String(page);if(p!=='1')return Response.success([],null);var q=thNfc(String(query||'').replace(/^\s+|\s+$/g,''));if(!q)return Response.success([],null);var urls=[BASE_URL+'/tim-kiem?keyword='+encodeURIComponent(q),BASE_URL+'/tim-kiem?q='+encodeURIComponent(q),BASE_URL+'/danh-sach/moi-cap-nhat'];for(var u=0;u<urls.length;u++){var d=thDoc(urls[u]);if(!d)continue;var a=thList(d);if(u<2&&a.length)return Response.success(a,null);var m=[];for(var i=0;i<a.length;i++)if(thMatch(a[i],q))m.push(a[i]);if(m.length)return Response.success(m,null);}return Response.success([],null);}
